/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BouquetRecord = IDL.Record({
  'id' : IDL.Text,
  'greenery' : IDL.Vec(IDL.Text),
  'imageKey' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'flowers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'createBouquet' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getBouquet' : IDL.Func([IDL.Text], [IDL.Opt(BouquetRecord)], ['query']),
  'getRecentBouquets' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BouquetRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BouquetRecord = IDL.Record({
    'id' : IDL.Text,
    'greenery' : IDL.Vec(IDL.Text),
    'imageKey' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'flowers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'createBouquet' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getBouquet' : IDL.Func([IDL.Text], [IDL.Opt(BouquetRecord)], ['query']),
    'getRecentBouquets' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BouquetRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };